feat(fonts): Iosevka fonts

diff --git a/waybar/switch_waybar b/waybar/switch_waybar
--- a/waybar/switch_waybar
+++ b/waybar/switch_waybar
@@ -13,16 +13,17 @@ EXISTING_STYLE=$(readlink "$STYLE")
 killall waybar
 
 [[ ! -e $OLD_STYLE || ! -e $NEW_STYLE || ! -e $OLD_CONFIG || ! -e $NEW_CONFIG ]] && {
-    echo "Missing style or config files."
-    exit 1
+  echo "Missing style or config files."
+  exit 1
 }
 
 if [[ "$EXISTING_STYLE" == "$OLD_STYLE" ]]; then
-    ln -sf "$NEW_CONFIG" "$CONFIG"
-    ln -sf "$NEW_STYLE" "$STYLE"
+  ln -sf "$NEW_CONFIG" "$CONFIG"
+  ln -sf "$NEW_STYLE" "$STYLE"
 else
-    ln -sf "$OLD_CONFIG" "$CONFIG"
-    ln -sf "$OLD_STYLE" "$STYLE"
+  ln -sf "$OLD_CONFIG" "$CONFIG"
+  ln -sf "$OLD_STYLE" "$STYLE"
 fi
 
-nohup waybar > /dev/null 2>&1 &
+nohup waybar >/dev/null 2>&1 &
+
